AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Scalable Chat Service
  
  SAM Template for event-driven chat service with REST API and worker functions.
  WebSocket API resources are in template-prod.yaml (requires LocalStack paid features).

Parameters:
  Environment:
    Type: String
    Default: local
    AllowedValues: [ local, dev, prod ]

  StateTableName:
    Type: String
    Default: "simplechat_connections"
    Description: (Required) The name of the new DynamoDB to store connection identifiers for each connected clients. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: "Required. Can be characters and underscore only. No numbers or special characters allowed."

  EventBusTableName:
    Type: String
    Default: "chat_events"
    Description: (Required) The name of the new DynamoDB to store. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: "Required. Can be characters and underscore only. No numbers or special characters allowed."

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: chat-service
        POWERTOOLS_METRICS_NAMESPACE: chat-service
        LOG_LEVEL: INFO
    CodeUri: ..

Resources:
  # DynamoDB Tables
  EventBusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "channel_id"
          AttributeType: "S"
        - AttributeName: "ts"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "channel_id"
          KeyType: "HASH"
        - AttributeName: "ts"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
      TableName: !Ref EventBusTableName

  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "connectionId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "connectionId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
      TableName: !Ref StateTableName

  # REST API Gateway
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'chat-rest-api-${Environment}'
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        ApiKeyRequired: false
      TracingEnabled: true

  # REST API Lambda Functions
  CreateConversationFunction:
    Type: AWS::Serverless::Function

    DependsOn: CreateConversationFunctionLogGroup
    Properties:
      FunctionName: !Sub 'chat-create-conversation-${Environment}'
      Handler: src.rest_api.handlers.create_conversation.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref EventBusTableName
          DYNAMODB_ENDPOINT_URL: ""
          LOG_LEVEL: INFO
      Events:
        CreateConversation:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /conversations
            Method: POST

  GetConversationFunction:
    Type: AWS::Serverless::Function

    DependsOn: GetConversationFunctionLogGroup
    Properties:
      FunctionName: !Sub 'chat-get-conversation-${Environment}'
      Handler: src.rest_api.handlers.get_conversation.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref EventBusTableName
          DYNAMODB_ENDPOINT_URL: ""
          LOG_LEVEL: INFO
      Events:
        GetConversation:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /conversations/{conversation_id}
            Method: GET

  SendMessageFunction:
    Type: AWS::Serverless::Function

    DependsOn: SendMessageFunctionLogGroup
    Properties:
      FunctionName: !Sub 'chat-send-message-${Environment}'
      Handler: src.rest_api.handlers.send_message.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref EventBusTableName
          DYNAMODB_ENDPOINT_URL: ""
          LOG_LEVEL: INFO
      Events:
        SendMessage:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /messages
            Method: POST

  GetMessagesFunction:
    Type: AWS::Serverless::Function

    DependsOn: GetMessagesFunctionLogGroup
    Properties:
      FunctionName: !Sub 'chat-get-messages-${Environment}'
      Handler: src.rest_api.handlers.get_messages.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref EventBusTableName
          DYNAMODB_ENDPOINT_URL: ""
          LOG_LEVEL: INFO
      Events:
        GetMessages:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /conversations/{conversation_id}/messages
            Method: GET

  GetChannelsFunction:
    Type: AWS::Serverless::Function

    DependsOn: GetChannelsFunctionLogGroup
    Properties:
      FunctionName: !Sub 'chat-get-channels-${Environment}'
      Handler: src.rest_api.handlers.get_channels.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref EventBusTableName
          DYNAMODB_ENDPOINT_URL: ""
          LOG_LEVEL: INFO
      Events:
        GetChannels:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /channels
            Method: GET

  SendChannelMessageFunction:
    Type: AWS::Serverless::Function

    DependsOn: SendChannelMessageFunctionLogGroup
    Properties:
      FunctionName: !Sub 'chat-send-channel-message-${Environment}'
      Handler: src.rest_api.handlers.send_channel_message.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref EventBusTableName
          DYNAMODB_ENDPOINT_URL: ""
          LOG_LEVEL: INFO
      Events:
        SendChannelMessage:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /channels/{channel_id}/messages
            Method: POST

  GetChannelMessagesFunction:
    Type: AWS::Serverless::Function

    DependsOn: GetChannelMessagesFunctionLogGroup
    Properties:
      FunctionName: !Sub 'chat-get-channel-messages-${Environment}'
      Handler: src.rest_api.handlers.get_channel_messages.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref EventBusTableName
          DYNAMODB_ENDPOINT_URL: ""
          LOG_LEVEL: INFO
      Events:
        GetChannelMessages:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /channels/{channel_id}/messages
            Method: GET

  # Log Groups for REST API Functions
  CreateConversationFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/chat-create-conversation-${Environment}'
      RetentionInDays: 7

  GetConversationFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/chat-get-conversation-${Environment}'
      RetentionInDays: 7

  SendMessageFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/chat-send-message-${Environment}'
      RetentionInDays: 7

  GetMessagesFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/chat-get-messages-${Environment}'
      RetentionInDays: 7

  GetChannelsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/chat-get-channels-${Environment}'
      RetentionInDays: 7

  SendChannelMessageFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/chat-send-channel-message-${Environment}'
      RetentionInDays: 7

  GetChannelMessagesFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/chat-get-channel-messages-${Environment}'
      RetentionInDays: 7

  # SSM parameter to share the REST API invoke URL with clients (frontend reads this)
  RestApiEndpointParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/chat/${Environment}/rest_api_endpoint"
      Type: String
      Description: REST API invoke URL for the chat service
      Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"

  # Worker Functions
  AgentFunction:
    Type: AWS::Serverless::Function

    DependsOn: AgentFunctionLogGroup
    Properties:
      FunctionName: !Sub 'chat-agent-worker-${Environment}'
      Handler: src.rest_api.workers.agent_worker.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 120
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref EventBusTableName
          DYNAMODB_ENDPOINT_URL: ""
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt EventBusTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 5

  DeliveryFunction:
    Type: AWS::Serverless::Function

    DependsOn: DeliveryFunctionLogGroup
    Properties:
      FunctionName: !Sub 'chat-delivery-worker-${Environment}'
      Handler: src.rest_api.workers.delivery_worker.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          CONNECTIONS_TABLE_NAME: !Ref StateTableName
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt EventBusTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 5

  # Log Groups for Worker Functions
  AgentFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/chat-agent-worker-${Environment}'
      RetentionInDays: 7

  DeliveryFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/chat-delivery-worker-${Environment}'
      RetentionInDays: 7

  # IAM Role for Lambda Functions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
      Policies:
        - PolicyName: LambdaDynamoDBPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Scan
                Resource:
                  - !GetAtt EventBusTable.Arn
                  - !GetAtt ConnectionsTable.Arn
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: !GetAtt EventBusTable.StreamArn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              # WebSocket API permissions (only used in production)
              - Effect: Allow
                Action:
                  - execute-api:ManageConnections
                Resource: '*'

Outputs:
  RestApiEndpoint:
    Description: REST API endpoint URL
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
    Export:
      Name: !Sub "${AWS::StackName}-RestApiEndpoint"

  ChatDataStateTableName:
    Value: !Ref EventBusTableName
    Description: DynamoDB table name for chat data
    Export:
      Name: !Sub "${AWS::StackName}-EventBusTableName"

  ConnectionsTableArn:
    Description: "Connections table ARN"
    Value: !GetAtt ConnectionsTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ConnectionsTableArn"

  AgentFunctionArn:
    Description: "Agent worker function ARN"
    Value: !GetAtt AgentFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-AgentFunctionArn"

  DeliveryFunctionArn:
    Description: "Delivery worker function ARN"
    Value: !GetAtt DeliveryFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DeliveryFunctionArn"
